# Read the Docs configuration file
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # Using a more stable Python version for RTD

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Don't fail the build because of warnings

# Optionally build your docs in additional formats
formats:
  - pdf

# Python requirements
python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-docs.txt
    - method: pip
      path: .