name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'retrosys/**'
      - 'README.md'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'retrosys/**'
      - 'README.md'
  workflow_dispatch:  # Allow manual workflow runs

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-docs.txt
        pip install -e .
    - name: Build documentation
      run: |
        cd docs
        make html
      continue-on-error: true  # Continue even if docs build fails
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/
        retention-days: 7